services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - /appdata/olivetin/config:/config # replace host path or volume as needed
    ports:
      - "1337:1337"
    restart: unless-stopped