services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    user: uid:gid
    volumes:
      - /etc/OliveTin:/config # replace host path or volume as needed
    ports:
      - "1337:1337"
    restart: unless-stopped