services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/New_York'
    volumes:
      - /etc/OliveTin:/config # replace host path or volume as needed
    ports:
      - "1337:1337"
    restart: unless-stopped